### ISSUE TITLE
Suggestion to make 'gene_cols' non-default when processing IRdata

### ISSUE THREAD

**Issue by nursyahr** [fahadahaf/chromir#1]
Dear authors, 

I would like to suggest that for the `process_IR` function, the `gene_cols` be made into a non-default argument instead since the 'Last_Intron' feature is optional according to the docs. I am assuming that `process_IR` is trying to compare the chromosomes at line 23: `if entry[gene_cols[0]] == element[gene_cols[1]]`.

```python
def create_dataset(IRdata, intragenicDHSs, load_from_file=False, save_data=True, remove_duplicates=True):
    if load_from_file:
        try:
            pos_data_V1 = np.loadtxt('final_overlapping_DHSs_IR_iDiffIR.txt',dtype=str) #these events (true positive) are those which overlap a DHS with the retained intron
            pos_data_V2 = np.loadtxt('final_overlapping_DHSs_IR_iDiffIR_V2.txt',dtype=str) #these events have a DHS not in retained intron but in the flanking exons so we still don't want any DHS overlapping these.
        except FileNotFoundError:
            print("DHS and IR overlapping files not found! set load_from_file=False to re-run the overlapping analysis.")
    else:
        gene_cols = [0, -1] if len(IRdata[0]) == 6 else [0,-2] # suggestion
        pos_data_V1, pos_data_V2 = process_IR(IRdata, intragenicDHSs, gene_cols, save_results=False)
```
Thank you.

**Comment by fahadahaf** [comment]
Thanks for the suggestion. In the most recent code push, I have added a new argument that will determine if your data includes first intron information as the last column. Here's an example:  
`python preprocess.py IR_file.txt intragenic_DHSs.bed false`  
In the above example, the last argument indicates that the IR data doesn't have first intron information (i.e. the last column has chromosome info).

Hope that is helpful,  
Fahad
